[package]
name = "ojichat_rs"
version = "0.1.0"
authors = ["Tatsumi Gamou <tatsumigamou@yahoo.co.jp>"]
description = '''
Ojisan Nanchatte (ojichat) command
Special Thanks to greymd (https://github.com/greymd)
'''
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
