name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish-crate:
    name: Publish crate
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: show rustfmt version
        with:
          command: fmt
          args: --version
      - uses: actions-rs/cargo@v1
        name: run rustfmt check
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: show clippy version
        with:
          command: clippy
          args: --version
      - uses: actions-rs/cargo@v1
        name: run clippy check
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: run cargo test
        with:
          command: test
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: publish crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          command: publish
